version: '3.9'

services:
#MongoDB services
 mongo_db:
  container_name: db_container
  image: mongo:latest
  restart: always
  volumes:
   - mongo_db:/data/db
   - /app/node_modules/nodemon/

 #Node API services

 api:
  build: .
  ports:
   - 4000:3000
  volumes:
   - ./:/usr/src/app
   - /usr/src/app/node_modules/nodemon/
  environment:
   PORT: 3000
   MONGO_URL: mongodb+srv://merjenmere:low5@cluster0.llgxazk.mongodb.net
   PASS_SEC: allgoodthings
   JWT_SEC: tothose

  depends_on:
   - mongo_db

volumes:
 mongo_db: {}
 

